In [8]:
import numpy as np
w=np.random.rand(3,)
R=np.random.rand(3,3)
r=np.random.rand(3,)
dr=np.random.rand(3,)
def skew(w):
    return np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
A = skew(-skew(w)@R@r+R@dr)@w
B = skew(w)@skew(w)@(R@r.reshape(-1,1))-skew(w)@R@dr.reshape(-1,1)
print(A)
print(B)
C = np.hstack([w,r,dr])
print(C)

[-0.36535359 -0.17809085  0.40210502]
[[-0.36535359]
 [-0.17809085]
 [ 0.40210502]]
[0.59136292 0.8372181  0.90811461 0.59362948 0.63244089 0.4014785
 0.421766   0.39256741 0.27722207]


In [7]:
miu = -np.array([1e-3, 1e-3, 1e-2]) #滚动阻力系数
shell_w = np.array([0,2.4,0])+w #球壳角速度
tau_contact = (miu*shell_w) #接触力矩 基座坐标系
print(miu, shell_w)
print(tau_contact)

[-0.001 -0.001 -0.01 ] [0.57922594 2.80048833 0.21513306]
[-0.00057923 -0.00280049 -0.00215133]
